### ISSUE TITLE
Drop bad records but continue

### ISSUE THREAD

**Issue by rmoff** [AgileWorksOrg/elasticsearch-river-csv#49]
I have a date field in my mapping and when the CSV file has a record that doesn't match it the whole river stops
It would be great if failed records could get written to a .bad file, and the original processing continue.

**Comment by vtajzich** [comment]
River is responsible for transferring data from CSV to ES only.

Bad lines are skipped (e.g. wrong number of columns) and logged.

Lines are being added to batch which is sent to ES later on (depends on number of lines in request, size etc). When this request fails because of wrong data types etc we cannot do anything about it.

I recommend to do some pre-processing and try to fix or filter bad lines. There are tools designed for this task.
